### ISSUE TITLE
Remove outliers in Preview plots

### ISSUE THREAD

**Issue by lweasel** [sidbdri/LAB-AID#4]
The main distribution plots have outliers hidden, using the "outlier.shape = NA" option of geom_boxplot(). I think that we should do the same for the plots in the Preview tab - unfortunately, it looks like there is some weird behaviour in plotly which stops this working?

https://github.com/ropensci/plotly/issues/1114

I wonder if we could try some of the workarounds suggested there?

**Comment by zkozic** [comment]
If I remember correctly, plotly does ignore outlier.shape argument. The only way to remove it was to remove a specific layer of the plot that contains the outlier points. On main plots it was always the same layer so it could be removed, but on Preview plots it somehow varied.

**Comment by lweasel** [comment]
Ok, it seems that we already went through this a while back and agreed that (i) there's not a lot that we can do about it, due to the behaviour of plotly (hopefully they might fix at some point), and (ii) that it was acceptable since it only affects the Preview plots. So I'll close this for now.

**Comment by lweasel** [comment]
I don't know if this has any value as a possible replacement for the interactivity provided by plotly:

https://davidgohel.github.io/ggiraph/index.html

Just noting it down in case we ever want to return to this.
