### ISSUE TITLE
Clarify averaging behaviour

### ISSUE THREAD

**Issue by lweasel** [sidbdri/LAB-AID#7]
Because of the way that data is transformed when "averaging" is turned on, it is possible for averaged graphs to fail to display in the "Data Plots" tab - this is because for a column to appear in the averaged data frame, it must appear in the "Averaging factors" factors box of the "Data Select" tab (this can be a bit counterintuitive – for example if factor F2 is nested within factor F1, and you want to average over F1 and plot over F2, then both F1 and F2 must be listed as averaging factors, not just F1).

Two possible ways of dealing with this:
- make factors not listed in "Averaging factors" appear in the averaged data frame ???
- adjust the dropdown selectors in the "Data Plots" tab to only include factors appearing in the averaged data frame (probably easier)

**Comment by zkozic** [comment]
Main effect and faceting factor selection drop-downs are now limited to averaging factors when averaged data is displayed.
