### ISSUE TITLE
Add information message in "Correlation" tab when there's only one variable

### ISSUE THREAD

**Issue by lweasel** [sidbdri/LAB-AID#8]
If there's only one variable in a data set, so that correlations can't actually be calculated, then the "Correlation" tab shows the dreaded Shiny error message "An error has occurred. Check your logs or contact the app author for clarification.". 

It'd be nice if we could replace this with a more informational message - or even grey out the tab's contents as well, if that is possible?

**Comment by zkozic** [comment]
Added a message if there's only one output variable.
