### ISSUE TITLE
Consider removing dependency on summarytools

### ISSUE THREAD

**Issue by lweasel** [sidbdri/LAB-AID#9]
We'd like to do this because:

a) summarytools has a dependency on tcl/tk, which requires the installation of XQuartz on MacOS for LAB-AID to run (although we don't use any of that functionality).
b) loading the summarytools library appears to prevent clean shutdown of the Shiny app when running from RStudio.

**Comment by zkozic** [comment]
This functionality is being removed as it causes more problems than it's worth. Might look into alternatives in the future.
